version: '3'

services:
  keycloak-db:
    container_name: postgres_keycloak
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      KEYCLOAK_DATABASE_HOST: keycloak_db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: postgres
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: root
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /realm-export.json
    ports:
      - "9091:8080"
    volumes:
      - D:/Employee-management/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - keycloak-db
    command:
      - start-dev --import-realm
    networks:
      - keycloak-network

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - keycloak-network

  agent:
    container_name: jenkins_agent
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTNGrXllb2n5XISBsBRdrwxTSV+R0vRSNYpAZlBbpiczTYZJcYNVXbpN0q4m9ryo/y8V4mDAblxQ0h19a6roXvlr9l/PQN4mHY68ISK8AiSBy49f6PRO6zr1Y+Qnjca5n3f6ytCVhD7lcn/EDPqEt1uE8PAsK54tySXNUYNifpmvJmAFLsarNKjurkySc1B2j+vzhtBIaqs1+gEKLwETdOyIq01Baz71Esx8YktuBGe5vb7lM4PptpXovQaJzjE8RVsEPq/VsigbS7HQRc99EvUrISf0bNHITJhfTXo86Iy+IXByhD4fdujARStOzLxTOYhvfgUJVtD5zdqK9PVAmKn+zkoaJDRt+sFbfC6w3kxaeQQvb4uWVYEkiVe9fp5vk3YjePmAbhjLyiaf0GAfcWChDdajt4F/NEp8ZFJeXliWaYmYrmsvvZMqEQT12osJBEs0jvrNMZ1JoX7me056gVRUrwZC8DSa/7zMcwZStxkZ4SoiOKHDTFWJyaIZHRfqM= jenkins@0cd61423c746

volumes:
  keycloak-db-data:
  jenkins_home:

networks:
  keycloak-network:
