version: '3'

services:
  keycloak-db:
    container_name: postgres_keycloak
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      my-network:
        ipv4_address: 172.20.0.2

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_IMPORT: /realm-export.json
    ports:
      - "9091:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - keycloak-db
    command:
      - start-dev --import-realm
    networks:
      my-network:
        ipv4_address: 172.20.0.3

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      my-network:
        ipv4_address: 172.20.0.4

  ubuntu:
    container_name: ubuntu
    image: ubuntu:latest
    command: sleep infinity
    networks:
      my-network:
        ipv4_address: 172.20.0.5

volumes:
  keycloak-db-data:
  jenkins_home:

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
